package com.tamelea.pm.nhpc;

/**
 * Fields for NHPC import.
 *
 */
enum NHPCField {
	LAST_NAME,
	FIRST_NAME,
	SUFFIX,
	SEX,
	NICKNAME,
	DATE_OF_BIRTH,
	AGE, //IGNORED
	STATUS,
	LAST_CHANGE_DATE,
	MIDDLE_NAME,
	MAIDEN_NAME,
	HOUSEHOLD_HEAD,
	HOME_PHONE,
	WORK_PHONE,
	MOBILE_PHONE,
	TITLE,
	ADDRESS,
	ADDRESS_2,
	CITY,
	STATE,
	POSTAL_CODE,
	COUNTRY,
	BIRTH_MONTH, //IGNORED
	PLACE_OF_BIRTH,
	BAPTISM,
	PROF_FAITH,
	PREV_MEMBERSHIP,
	ECCLES_OFFICE,
	DATE_OF_MARR,
	SPOUSE,
	DIVORCE,
	EDUCATION,
	EMPLOYER,
	DATE_RECEIVED,
	DATE_DISMISSED,
	DISMISSED_TO,
	DISCIPLINE,
	DATE_OF_DEATH,
	TOTAL, //IGNORED
	TODAYS_DATE, //IGNORED
	YRS_MEMBER, //IGNORED
	YRS_MARRIED, //IGNORED
	EMAIL,
	WORK_EMAIL,
}
